### ISSUE TITLE
How to define 'LOGSTASH_CORE_PATH'?

### ISSUE THREAD

**Issue by zhihui-ge** [logstash-plugins/logstash-codec-java_codec_example#2]
Could not get unknown property 'LOGSTASH_CORE_PATH' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
Open File

compile fileTree(dir: LOGSTASH_CORE_PATH, include: "**/logstash-core-?.?.?.jar")

**Comment by danhermann** [comment]
@zhihui-ge, thank you for trying the new codec API. Unfortunately, it was the last part of the API to get full documentation, so the instructions for defining `LOGSTASH_CORE_PATH` were not included in this release but will be included in the upcoming 6.7 release of Logstash. 

Briefly, you need to create a file named `gradle.properties` that defines `LOGSTASH_CORE_PATH` as the path to a local copy of the Logstash codebase. This is properly documented for the filter plugin at the link below if you wish to refer to that:

https://www.elastic.co/guide/en/logstash/6.6/java-filter-plugin.html#_set_up_your_environment_2

I'm going to close this issue for now, but if you have any other problems, please let us know either with an issue here or by posting a question in this forum thread: https://discuss.elastic.co/t/ama-java-plugins-in-logstash/171535
